### ISSUE TITLE
Read me file

### ISSUE THREAD

**Issue by abinroy04** [hobbica98/ClickToChat-BetterDiscord-Plugin#1]
Hey Man, 
would be helpful if you added a description on a Readme file so that we know what the plugin does exactly.

**Comment by PokeDerg** [comment]
Go to a server dm and it adds a button to go to that user's dms
![image](https://user-images.githubusercontent.com/80658697/126805885-a98d667e-4f92-40d7-8aeb-08b45941d8ca.png)

**Comment by SoWhoYou** [comment]
> Go to a server dm and it adds a button to go to that user's dms
> ![image](https://user-images.githubusercontent.com/80658697/126805885-a98d667e-4f92-40d7-8aeb-08b45941d8ca.png)

That has got to be the absolute worst instructions I've ever seen for a plugin.
Removing this now because it's nearly impossible to figure out how to use.

**Comment by PokeDerg** [comment]
sorry i mean go to the server vc and accedently typed dm, go to a server vc and other people have a button next to there name you can click

**Comment by Overimagine1** [comment]
I created a PR to add a readme, now I'm just waiting for hobbica to merge it.

**Comment by abinroy04** [comment]
I'm just confused now.
