### ISSUE TITLE
Not clickable when someone is live in vc on hover.

### ISSUE THREAD

**Issue by precompile** [hobbica98/ClickToChat-BetterDiscord-Plugin#5]
I have an issue with this plugin and when someone in vc is live. It is no longer clickable when hovering above a livestream.
![image](https://user-images.githubusercontent.com/81035179/222753783-33af6308-3e3f-4a49-a629-53aace523d50.png)
![image](https://user-images.githubusercontent.com/81035179/222753837-01a24d49-05a0-48c5-a223-ae7284fb589b.png)

**Comment by hobbica98** [comment]
Should be fixed in version 1.0.3
