### ISSUE TITLE
New restyled version

### ISSUE THREAD

**Issue by nicola02nb** [hobbica98/ClickToChat-BetterDiscord-Plugin#7]
@hobbica98  @Overimagine1 I created a PR  #6  where I restyled the chat button, feel free to test and give an opinion...

**Comment by Overimagine1** [comment]
I have stopped using BetterDiscord a while ago.

**Comment by nicola02nb** [comment]
Mh can you a least accept my PR to publish the newer version?
Or I have to wait for @hobbica98 approval?

**Comment by Overimagine1** [comment]
[All I did was make a readme lol](https://github.com/hobbica98/ClickToChat-BetterDiscord-Plugin/commit/2c5d84c48d0fffb04a4963d56feacfdcc32e0f7a). I don't actually develop the plugin
